#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapExtensionsMVC.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using BootstrapExtensionsMVC;
    using BootstrapExtensionsMVC.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Boolean.cshtml")]
    public partial class Boolean_ : System.Web.Mvc.WebViewPage<Boolean>
    {
        public Boolean_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
  
    var templateHelper = new BootstrapExtensionsMVC.Helpers.EditorTemplateHelper(ViewBag.formGroupSize, ViewBag.labelWidth);
    var checkboxStyle = ViewBag.checkboxStyle;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteAttribute("class", Tuple.Create(" class=\"", 205), Tuple.Create("\"", 306)
, Tuple.Create(Tuple.Create("", 213), Tuple.Create("form-group", 213), true)
            
            #line 8 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
, Tuple.Create(Tuple.Create(" ", 223), Tuple.Create<System.Object, System.Int32>(templateHelper.FormGroupCssClass
            
            #line default
            #line hidden
, 224), false)
            
            #line 8 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
, Tuple.Create(Tuple.Create(" ", 257), Tuple.Create<System.Object, System.Int32>(Html.ValidationErrorFor(m => m, " has-error")
            
            #line default
            #line hidden
, 258), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 10 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
      
        if (string.IsNullOrEmpty(templateHelper.LabelCssClass))
        {
            
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
       Write(Html.Raw("<div class=\"col-md-12\">"));

            
            #line default
            #line hidden
            
            #line 13 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                                      ;
            
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
       Write(Html.Raw("<div class=\"checkbox " + checkboxStyle + "\">"));

            
            #line default
            #line hidden
            
            #line 14 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                                                       ;
                
                
            
            #line default
            #line hidden
            
            #line 16 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                              
                
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
           Write(Html.CheckBoxFor(m => m));

            
            #line default
            #line hidden
            
            #line 17 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                          ;
                                          
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                     Write(Html.LabelFor(m => m, new { @class = "control-label " + templateHelper.LabelCssClass }));

            
            #line default
            #line hidden
            
            #line 18 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                                                                                                                  ;
            
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
       Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 19 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                               ;
        }
        else
        {
         
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
    Write(Html.LabelFor(m => m, new { @class = "control-label " + templateHelper.LabelCssClass }));

            
            #line default
            #line hidden
            
            #line 23 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                                                                                  
         
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
    Write(Html.Raw("<div class=\"" + @templateHelper.FieldCssClass + " checkbox " + checkboxStyle + " \">"));

            
            #line default
            #line hidden
            
            #line 24 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                                                                                            
         
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
    Write(Html.Raw("&nbsp; &nbsp;"));

            
            #line default
            #line hidden
            
            #line 25 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                    
         
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
    Write(Html.CheckBoxFor(m => m));

            
            #line default
            #line hidden
            
            #line 26 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                   

            
            #line default
            #line hidden
WriteLiteral("            <label></label>\r\n");

            
            #line 28 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
        }


        
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
   Write(Html.ValidationMessageFor(m => m, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 31 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                                                                                ;

        
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
   Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 33 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Boolean.cshtml"
                           ;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
