#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapExtensionsMVC.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using BootstrapExtensionsMVC;
    using BootstrapExtensionsMVC.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Int32.cshtml")]
    public partial class Int32_ : System.Web.Mvc.WebViewPage<object>
    {
        public Int32_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
  
    var templateHelper = new BootstrapExtensionsMVC.Helpers.EditorTemplateHelper(ViewBag.formGroupSize, ViewBag.labelWidth);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteAttribute("class", Tuple.Create(" class=\"", 156), Tuple.Create("\"", 257)
, Tuple.Create(Tuple.Create("", 164), Tuple.Create("form-group", 164), true)
            
            #line 7 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
, Tuple.Create(Tuple.Create(" ", 174), Tuple.Create<System.Object, System.Int32>(templateHelper.FormGroupCssClass
            
            #line default
            #line hidden
, 175), false)
            
            #line 7 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
, Tuple.Create(Tuple.Create(" ", 208), Tuple.Create<System.Object, System.Int32>(Html.ValidationErrorFor(m => m, " has-error")
            
            #line default
            #line hidden
, 209), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 9 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
      
        if (string.IsNullOrEmpty(templateHelper.LabelCssClass))
        {
            
            
            #line default
            #line hidden
            
            #line 12 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
       Write(Html.Raw("<div class=\"col-md-12\">"));

            
            #line default
            #line hidden
            
            #line 12 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
                                                  ;
        
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
   Write(Html.LabelFor(m => m, new { @class = "control-label " + templateHelper.LabelCssClass }));

            
            #line default
            #line hidden
            
            #line 13 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
                                                                                                ;
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 17 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
       Write(Html.LabelFor(m => m, new { @class = "control-label " + templateHelper.LabelCssClass }));

            
            #line default
            #line hidden
            
            #line 17 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
                                                                                                    ;
        
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
   Write(Html.Raw("<div class=\"" + @templateHelper.FieldCssClass + "\">"));

            
            #line default
            #line hidden
            
            #line 18 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
                                                                          ;
        }

        
            
            #line default
            #line hidden
            
            #line 21 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
   Write(Html.TextBoxFor(m => m, new { @class = "form-control" }));

            
            #line default
            #line hidden
            
            #line 21 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
                                                                 ;
        
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
   Write(Html.ValidationMessageFor(m => m, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 22 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
                                                                                ;

        
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
   Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 24 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Int32.cshtml"
                           ;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
