#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapExtensionsMVC.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using BootstrapExtensionsMVC;
    using BootstrapExtensionsMVC.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Text.cshtml")]
    public partial class Text_ : System.Web.Mvc.WebViewPage<object>
    {
        public Text_()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
  
    var templateHelper = new BootstrapExtensionsMVC.Helpers.EditorTemplateHelper(ViewBag);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteAttribute("class", Tuple.Create(" class=\"", 124), Tuple.Create("\"", 225)
, Tuple.Create(Tuple.Create("", 132), Tuple.Create("form-group", 132), true)
            
            #line 8 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
, Tuple.Create(Tuple.Create(" ", 142), Tuple.Create<System.Object, System.Int32>(templateHelper.FormGroupCssClass
            
            #line default
            #line hidden
, 143), false)
            
            #line 8 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
, Tuple.Create(Tuple.Create(" ", 176), Tuple.Create<System.Object, System.Int32>(Html.ValidationErrorFor(m => m, " has-error")
            
            #line default
            #line hidden
, 177), false)
);

WriteLiteral(">\r\n\r\n");

            
            #line 10 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
      
        if (string.IsNullOrEmpty(templateHelper.LabelCssClass))
        {
            
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
       Write(Html.Raw("<div class=\"col-md-12\">"));

            
            #line default
            #line hidden
            
            #line 13 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
                                                  ;
            
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
       Write(Html.LabelFor(m => m, templateHelper.LabelHtmlAttributes));

            
            #line default
            #line hidden
            
            #line 14 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
                                                                      ;
        }
        else
        {
            
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
       Write(Html.LabelFor(m => m, templateHelper.LabelHtmlAttributes));

            
            #line default
            #line hidden
            
            #line 18 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
                                                                      ;
            
            
            #line default
            #line hidden
            
            #line 19 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
       Write(Html.Raw("<div class=\"" + @templateHelper.FieldCssClass + "\">"));

            
            #line default
            #line hidden
            
            #line 19 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
                                                                              ;
        }
        
        
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
   Write(Html.TextBoxFor(m => m, templateHelper.InputHtmlAttributes));

            
            #line default
            #line hidden
            
            #line 22 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
                                                                    ;
        
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
   Write(Html.ValidationMessageFor(m => m, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 23 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
                                                                                ;

        
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
   Write(Html.Raw("</div>"));

            
            #line default
            #line hidden
            
            #line 25 "C:\Users\rich\My Dev Space\trunk\BootstrapExtensionsMVC\BootstrapExtensionsMVC\Views\Shared\EditorTemplates\Text.cshtml"
                           ;
    
            
            #line default
            #line hidden
WriteLiteral("   \r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
